---
title: "HW6"
author: "Taisiya Glazova"
date: "2024-04-17"
output: html_document
---

## Загрузка библиотек

```{r}
library(tidyverse)
```

## Показатели от спонсора

```{r}
power = 0.8 # Мощность
alpha = 0.05 # Уровень значимости
drop_out_rate = 0.1 # Ожидаемый процент пропущенных значений
```

# Задание 1

```{r echo=TRUE}
sigma = 0.20 # Дисперсия
margin = -0.10 # Разница средних
delta = 0.25 # Клинически значимая разница

# Расчёт размера выборки
n <- (qnorm(1 - alpha/2)+qnorm(power))^2*sigma^2/(2*(delta-abs(margin)))^2

# Поправка на пропущенные значения
n <- (n / (1 - drop_out_rate)) %>%
  ceiling()

# Вывод результатов
cat('Размер выборки для каждой группы должен быть равен', n)
cat('\n')
cat('Суммарный размер групп должен быть', n*2)

```

# Задание 2

```{r echo=TRUE}
sigma = -0.1 # Клинически значимая разница
p2 = 0.65 # Доля ответов для тестового препарата
p1 = 0.85 # Доля ответов для препарата сравнения
k=1 # Соотношение групп

# Расчёт размера выборки
n <- ((qnorm(1 - alpha/2)+qnorm(power))^2 * (p1*(1-p1) + p2*(1-p2))) / (p1-p2-sigma)^2

# Поправка на пропущенные значения
n <- (n / (1 - drop_out_rate)) %>%
  ceiling()

# Вывод результатов
cat('Размер выборки для каждой группы должен быть равен', n)
cat('\n')
cat('Суммарный размер групп должен быть', n*2)


```

# Задание 3

```{r echo=TRUE}
hr = 2 # Отношение рисков "золотой стандарт/новая терапия"
d = 0.8 # Предполагаемая доля пациентов, сталкивающихс с заболеванием
# Соотношения групп терапии
p1 = 0.5  
p2 = 0.5

# Расчёт размера выборки
n <- (qnorm(1 - alpha/2)+qnorm(power))^2 / (log(hr)^2 * p1*p2*d)

# Поправка на пропущенные значения
n <- (n / (1 - drop_out_rate)) %>%
  ceiling()

# Вывод результатов
cat('Размер выборки для каждой группы должен быть равен', n)
cat('\n')
cat('Суммарный размер групп должен быть', n*2)

```
